### ISSUE TITLE
Bug: creation wallet with data (private key) failed

### ISSUE THREAD

**Issue by remboshelby** [weishirongzhen/flutter_trust_wallet_core_lib_include#3]
Description: I try to сreate wallet with private key (method HDWallet.createWithData(formatPrivateKey)) but it always failed on this method call. Problem is exist on both platforms (Android/iOS)

Error report:
`
I/flutter (20041): Invalid argument(s): Failed to lookup symbol (undefined symbol: TWHDWalletCreateWithData)
I/flutter (20041): 
I/flutter (20041): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
I/flutter (20041): #1      TWHDWallet._TWHDWalletCreateWithData_ptr (package:flutter_trust_wallet_core/ffi_impl/tw_hd_wallet.dart:60:60)
I/flutter (20041): #2      TWHDWallet._TWHDWalletCreateWithData_ptr (package:flutter_trust_wallet_core/ffi_impl/tw_hd_wallet.dart)
I/flutter (20041): #3      TWHDWallet._TWHDWalletCreateWithData (package:flutter_trust_wallet_core/ffi_impl/tw_hd_wallet.dart:61:80)
I/flutter (20041): #4      TWHDWallet._TWHDWalletCreateWithData (package:flutter_trust_wallet_core/ffi_impl/tw_hd_wallet.dart)
I/flutter (20041): #5      TWHDWallet.TWHDWalletCreateWithData (package:flutter_trust_wallet_core/ffi_impl/tw_hd_wallet.dart:54:12)
I/flutter (20041): #6      TWHDWalletImpl.createWithData (package:flutter_trust_wallet_core/dart_impl/tw_hd_wallet_impl.dart:25:31)
I/flutter (20041): #7      new HDWallet.createWithData (package:flutter_trust_wallet_core/core/hd_wallet.dart:21:36)
I/flutter (20041): #8      ImportWalletServiceImpl.importMultiCurrencyByPrivateKeyWallet (package:mobile_app/layers/services/wallet/impl/import.dart:67:31)
I/flutter (20041): #9      WalletUseCaseImpl
`
Expected behavior: Successfully created wallet by private key.

Probable solution:
I think that garbage collector remove some "useless" function when you build artifacts
Can you fix this?

**Comment by weishirongzhen** [comment]
1: what device your are running at? if android, look in to 2.
2:did you use official android lib?, if yes, it will cause "Failed to lookup symbol"  because offcial lib build android lib hide native api by default, you need to rebuild it by change  "CMakeLists.txt" line 14 to
` "set(CMAKE_CXX_VISIBILITY_PRESET defult)" `
android rebuild it.  or use my lib in this project [https://github.com/weishirongzhen/flutter_trust_wallet_core_lib_include](https://github.com/weishirongzhen/flutter_trust_wallet_core_lib_include)

**Comment by remboshelby** [comment]
1. Im running on Android (8.0.0) and iPhone 11 (iOS 15.1). I have with bug on both devices.
2. Im using your lib from repository  https://github.com/weishirongzhen/flutter_trust_wallet_core_lib_include
<img width="775" alt="image" src="https://user-images.githubusercontent.com/35132722/142830422-919486d9-3109-4295-9194-e87ff822b1ce.png">

**Comment by weishirongzhen** [comment]
could you paste your full  sample code?

**Comment by remboshelby** [comment]
here it is 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/35132722/142831225-8dba68b2-5ea3-40e4-a08d-28d0756bc656.png">

other functions working fine

**Comment by weishirongzhen** [comment]
api change , please pull new code to try again

**Comment by remboshelby** [comment]
I will check this for an hour! Thanks!

**Comment by remboshelby** [comment]
@weishirongzhen work fine! Thanks!
